# Generated by Django 4.1.3 on 2022-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('publishedDate', models.DateField()),
                ('genre', models.CharField(choices=[('HORROR', 'Horror'), ('ROMANCE', 'Romance'), ('ADVENTURE', 'Adventure')], max_length=200)),
                ('photoURL', models.CharField(default='https://demo.publishr.cloud/assets/common/images/edition_placeholder.png', max_length=400)),
                ('quantityLeft', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
