# Generated by Django 4.1.3 on 2022-12-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='deleted',
        ),
    ]
